config/routes.rb
Rails.application.routes.draw do

  get 'user_sessions/destroy'

  get 'user_sessions/new'

  get 'user_sessions/destor'

  get "upload" => "images#new", :as => "upload"

  get 'images/create'

  get 'images/destroy'

  get 'images/index'

  get 'categories/new'

  get 'categories/create'

  get 'categories/edit'

  get 'categories/update'

  get 'categories/destroy'

  get 'categories/show'

  get "/login" => 'user_sessions#new', as: :login
  delete "/logout" => 'user_sessions#destroy', as: :logout 

  resources :images, :categories, :users 
  resources :user_sessions, only: [:new, :create] 
  resources :password_resets, only: [:new, :create, :edit, :update]

  root 'user_sessions#new'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :images 
end

app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :category

	mount_uploader :image, ImageUploader

	before_save :update_image_attributes

	private
		def update_image_attributes
			if image.present? && image_changed?
				self.image_content_type = image.file.content_type
				self.image_file_size = image.file.size
			end 
		end 
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :email, presence: true,
					  uniqueness: true,
					  format: {
					  	with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9\.-]+\.[A-Za-z]+\Z/
					  }
	validates :first_name, presence: true
	validates :last_name, presence: true

	before_save :downcase_email 


	def full_name 
		self.first_name + " " + self.last_name
	end 

	def downcase_email 
		self.email = email.downcase
	end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :getCategoryNav
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def getCategoryNav
  	@categoryNav = Category.all
  end 

  def logged_in?
      current_user
    end
    helper_method :logged_in?
    def current_user
    	@current_user ||= User.find(session[:user_id]) if session[:user_id] 
    end 

    def require_user
    	if current_user 
    		true
    	else
    		redirect_to login_path, notice: "You must be logged in to access that page." 
    	end 
    end 

    def require_admin
      if current_user.admin == true 
        true
      else 
        false
      end 
    end 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user 
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category Created"
      redirect_to category_path(@category.id)
    else 
      render 'new'
    end 
  end

  def edit
    @category = Category.find(params[:id])
    @categories = Category.all
    @images = @category.images 
  end

  def update
    @category = Category.find(params[:id])


    if @category.update(category_params)
      flash[:notice] = "Category Updated"
      redirect_to category_path(params[:id])
    else
      render 'edit'
    end 
  end

  def destroy
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @images = @category.images.order("RANDOM()") 
  end

  private 
    def category_params
      params.require(:category).permit(:name)
    end 
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :require_user 
  def new
  	@image = Image.new
  end

  def create
  	@image = Image.new(image_params)

  	if @image.save
  		flash[:notice] = "Image Created"
  		redirect_to root_path
  	else
  		render 'new'
  	end 
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy

    flash[:notice] = "Image Removed"

    redirect_to images_path
  end

  def index
    @images = Image.all.order("RANDOM()") 
    @categories = Category.all 
  end

  private
  	def image_params
  		params.require(:image).permit(:image, :category_id, :image_title, :image_description, :image_file_size, :image_content_type, :remote_image_url)
  	end 
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController


  def new
    if logged_in? 
      redirect_to images_path 
    else 
      render 'new' 
    end 
  end

  def create
  	user = User.find_by(email: params[:email]) 
  	if user && user.authenticate(params[:password]) 
  		session[:user_id] = user.id 
  		flash[:success] = "Thanks for logging in!" 
  		redirect_to root_path 
  	else 
  		flash[:error] = "There was a problem logging in. Please check your email and password." 
  		render action: 'new' 
  	end 
  end

  def destroy
    session[:user_id] = nil
    reset_session
    redirect_to root_path, notice: "You have been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy, :import]

	def new
		@user = User.new
	end 

	def index
		@users = User.all
	end 

	def edit
	end 

	def create 
		@user = User.new(user_params)

		respond_to do |format|
			if @user.save
				#session[:user_id] = @user.id 
				format.html { redirect_to users_path, notice: 'User was successfully created.'}
				format.json { render action: 'show', status: :created, location: @user }
			else 
				format.html { render :new }
        		format.json { render json: @user.errors, status: :unprocessable_entity }
        	end 
		end 

	end 

	def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
 

    end

  	end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



	private 
		def set_user
			@user = User.find(params[:id])
		end 

		def user_params
      		params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :stripe_token)
    	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
	def current_user
		if (user_id = session[:user_id]) 
			@current_user ||= User.find_by(id: session[:user_id])
		elsif (user_id = cookies.signed[:user_id])
			user = User.find_by(id: user_id)
			if user && user.authenticated?(:remember, cookies[:remember_token])
				log_in user
				@current_user = user
			end 
		end 
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= form_for @category do |f| %> 
	<!-- Check fof errors --> 
	<% if @category.errors.any? %> 
		<% @category.errors.full_messsages.each do |msg| %> 
			<!-- Show errors --> 
			<div class="alert alert-danger"><%= msg %></div> 
		<% end %> 
	<% end %> 

	<div class="form-group">
		<%= f.label :name %> 
		<%= f.text_field :name, class: 'form-control' %> 
	</div> 
	<br> 
	<%= f.submit "Submit", class: 'btn btn-primary' %> 
	<%= link_to "Cancel", categories_path, class: 'btn btn-default' %> 
<% end %> 

<h3 class="page-header">Images in <%= @category.name %></h3> 
<div id="edit_images"> 
	<% if @images.exists? %> 
		<% @images.each_slice(6) do |image| %> 
			<div class="row"> 
				<% image.each do |image| %> 
					<div class="col-md-2">
						<%= image_tag image.image_url(:thumb) %> 
						<center><%= link_to "Delete", image_path(image), class: 'delete', method: :delete, data: {confirm: "Are you sure?"} %></center> 
					</div> 
				<% end %> 
		<% end %> 
	<% end %> 

</div> 

app/views/categories/new.html.erb
<h2>Add New Category</h2>

<%= form_for @category do |f| %> 
	<!-- Check fof errors --> 
	<% if @category.errors.any? %> 
		<% @category.errors.full_messsages.each do |msg| %> 
			<!-- Show errors --> 
			<div class="alert alert-danger"><%= msg %></div> 
		<% end %> 
	<% end %> 

	<div class="form-group">
		<%= f.label :name %> 
		<%= f.text_field :name, class: 'form-control' %> 
	</div> 
	<br> 
	<%= f.submit "Submit", class: 'btn btn-primary' %> 
	<%= link_to "Cancel", categories_path, class: 'btn btn-default' %> 
<% end %> 

app/views/categories/show.html.erb
<div id="gallery">
      <h2><%= @category.name %> <% if current_user.admin? %> <small class="pull-right"><%= link_to 'Edit', edit_category_path %></small> <% end %></h2>
      <% if @images.exists? %> 
        <% @images.each_slice(4) do |image| %> 
          <div class="row"> 
            <% image.each do |image| %>
              <div class="col-md-3">
              <div class="photo photo-type-line">
                <a href="<%= image.image_url() %>" class="photo-hover" data-lightbox="my-images" data-title="<%= image.image_title %>">
                  <div class="photo-info <%= image.image_title %>">
                    <div class="headline"><%= image.image_title %></div>
                    <div class="line"></div>
                    <div class="desc"><%= image.image_description %></div>
                  </div>
                  <div class="mask"></div>
                </a>
                <div class="photo-img"><%= image_tag image.image_url(:thumb) %></div>
              </div>
            </div>
           <% end %> 
          </div> 
      <% end %> 
 
    <% else %> 
      <p> There are no images</p> 
    <% end %>            
</div>

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/destroy.html.erb
<h1>Images#destroy</h1>
<p>Find me in app/views/images/destroy.html.erb</p>

app/views/images/index.html.erb
<div id="gallery">
      <h2>All Images</h2>
      <% if @images.exists? %> 
        <% @images.each_slice(4) do |image| %> 
          <div class="row"> 
            <% image.each do |image| %>
              <div class="col-md-3">
              <div class="photo photo-type-line">
                <a href="<%= image.image_url() %>" class="photo-hover" data-lightbox="my-images" data-title="<%= image.image_title %>">
                  <div class="photo-info">
                    <div class="headline"><%= image.image_title %></div>
                    <div class="line"></div>
                    <div class="desc"><%= image.image_description %></div>
                  </div>
                  <div class="mask"></div>
                </a>
                <div class="photo-img"><%= image_tag image.image_url(:thumb) %></div>
              </div>
            </div>
           <% end %> 
          </div> 
      <% end %> 
 
    <% else %> 
      <p> There are no images</p> 
    <% end %>            
</div>

app/views/images/new.html.erb
<h2>Upload Image</h2> 

<%= form_for @image, :html => {:multipart => true} do |f| %>
	<!-- Check for errors --> 
	<% if @image.errors.any? %> 
		<% @image.errorrs.full_messages.each do |msg| %> 
			<!-- Show errors --> 
			<div class="alert alert-danger"><%= msg %></div> 
		<% end %> 
	<% end %> 

	<div class="form-group"> 
		<%= f.label :image_title %> 
		<%= f.text_field :image_title , class: 'form-control' %> 
	</div> 

	<div class="form-group"> 
		<%= f.label :category %> 
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {
			:include_blank => 'Select One'}, class: 'form-control' %> 
	</div> 

	<div class="form-group"> 
		<%= f.label :image_description %> 
		<%= f.text_area :image_description, class: 'form-control' %>
	</div> 

	<div class="form-group">
		<%= f.label :image %> 
		<%= f.file_field :image %> 
	</div> 

	<div class="form-group"> 
		<%= f.label :remote_image_url, 'or image url' %> 
		<%= f.text_field :remote_image_url, class: 'form-control' %> 
	</div> 
	<br> 

	<%= f.submit "submit", class: 'btn btn-primary' %> 
	<%= link_to "Cancel", images_path, class: 'btn btn-default' %> 
<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chip Duffield Photos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrapper"> 
   
      <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">Chip's Photo Gallery</a>
              </div>
              <div id="navbar" class="collapse navbar-collapse">
                <% if logged_in? %> 
                  <ul class="nav navbar-nav">
                    <li><%= link_to "Home", root_path %></li>
                    <% @categoryNav.each do |category| %>
                    	<li><%= link_to category.name, category_path(category.id) %></li>
                    <% end %>
                  </ul>
                <% end %> 
                <ul class="nav navbar-nav pull-right">
                  <% if logged_in? %> 
                    <% if current_user.admin? %> 
                      <li><%= link_to "Upload Photo", upload_path %></li>
                      <li><%= link_to "Add Category", new_category_path %></li>
                    <% end %> 
                    <li class="dropdown">
                    <a href='#' class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile", current_user %></li>
                      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                      <% if current_user.admin? %> 
                        <li><%= link_to "Manage Users", users_path %></li> 
                      <% end %> 
                      <li class="divider"></li>
                      <li><%= link_to "Log Out", logout_path, method: :delete %></li>
                    </ul>
                    </li> 
                  <% end %> 
                </ul>
              </div><!--/.nav-collapse -->
            </div>
          </nav>


    <div id="content"> 
        <section >
          <div class="container">
          	<!-- Alerts & Messages -->
            <% if flash[:notice] %>
              <div class="alert alert-success"><%= flash[:notice] %></div>
            <% end %>

            <% if flash[:alert] %>
              <div class="alert alert-danger"><%= flash[:alert] %></div>
            <% end %>
            <%= yield %>
          </div><!-- /.container -->
        </section>
      </div> 

<!--     <div id="footer">  
  
            <p>Copyright &copy; 2015, Chip Duffield</p>

    </div>  -->
  </div> 
</body>
</html>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Log In</h1>

 


<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_tag user_sessions_path do %>

				<div class='form-group'>
					<div class="input"> 
					<%= text_field_tag :email, params[:email], class: 'form-control', :placeholder => "Email Address"  %> 
					</div> 
				</div> 
		 
				<div class='form-group'> 
					<div class="input"> 
					<%= password_field_tag :password, "", placeholder: "Password", class: 'form-control' %> 
					</div> 
				</div> 
		

			<%= submit_tag "Log In", class: "btn btn-lg btn-primary" %> 
			<%= link_to "Forgot Password", new_password_reset_path %> 
		<% end %> 
	</div>
</div>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <fieldset>
      <%= form_for user, :html => {:class => 'form-stacked'} do |f| %>
        <% if user.errors.any? %>
          <div class="alert-message block-message error">
            <p><%= "#{pluralize(user.errors.count, "problem")} with your registration:" %></p>
            <div class="errors">
              <% user.errors.full_messages.each do |msg| %>
                <p><%= msg %></p>
              <% end %>
            </div>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :first_name %>
          <div class="input">
            <%= f.text_field :first_name, :class => "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :last_name %>
          <div class="input">
            <%= f.text_field :last_name, :class => "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :email %>
          <div class="input">
            <%= f.text_field :email, :class => "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <% if defined? editing %>
            <span class="help-block">Leave blank to keep your current password</span>
          <% end %>
          <%= f.label :password %>
          <div class="input">
            <%= f.password_field :password, :class => "form-control" %> 
          </div>
        </div>

        <div class="form-group">
          <%= f.label :password_confirmation %>
          <div class="input">
            <%= f.password_field :password_confirmation, :class => "form-control" %>
          </div>

        </div>
      
        <div class="actions">
          <%= f.submit((defined?(editing) ? "Update" : "Register"), :class => "btn btn-primary") %>
        </div>
      <% end %>
    </fieldset>
    <br /> 
  </div>
</div>

app/views/users/edit.html.erb
<div class="page-header">
  <h1>Edit Profile</h1>
</div>

<%= render :partial => 'users/form', :locals => {:user => current_user, :editing => true} %>

app/views/users/index.html.erb
<% if current_user.admin? %> 
	<% if @users.exists? %> 
		<div class="row"> 
			<div> 
				<table class="table table-striped table-bordered"> 
					<thead> 
						<tr> 
							<th>Name</th> 
							<th>Email</th> 
							<th></td> 
						</tr> 
					</thead> 
					<tbody> 
					<% @users.each do |user| %> 
						<tr> 
							<td><%= user.full_name %></td> 
							<td><%= user.email %></td> 
							<td><%= link_to "Delete", user, method: :delete, data: { confirm: "Are you sure?" } %> </td> 
						</tr> 
					<% end %> 
					</tbody> 
				</table> 
			</div> 
		</div> 
	<% end %> 
	<p>
		<%= link_to "New User", new_user_path, :class => "btn btn-primary" %>
	</p> 
<% else %> 
	<p>You do not have permisssions to view that page</p> 
<% end %> 

app/views/users/new.html.erb
<% if current_user.admin? %> 
	<div class="page-header">
	  <h1>Register</h1>
	</div>

	<%= render :partial => 'users/form', :locals => {:user => @user} %>
<% else %> 
	<p>You do not have permisssions to view that page</p> 
<% end %> 

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row"> 
	<div class="col-md-4 col-md-offset-4"> 
		<h2>Profile</h2> 
		<p>
		  <strong>First name:</strong>
		  <%= @user.first_name %>
		</p>

		<p>
		  <strong>Last name:</strong>
		  <%= @user.last_name %>
		</p>

		<p>
		  <strong>Email:</strong>
		  <%= @user.email %>
		</p>




		<%= link_to 'Edit', edit_user_path(@user) %> 
	</div> 
</div> 